### ISSUE TITLE
US 01.08.02

### ISSUE THREAD

**Issue by cmmartin2514** [CMPUT301F21T36/OldHabitsDieHard#39]
**Focus:**
Habits

**Partial User Story:**
As a doer, I want to manually reorder habits on my list of habits.

**Rationale:**
- To organize the habits the way the user wants

**Clarifications:**

**Story Points:**
4

**Risk Level:**
Medium

**Testing:**
- Create some habits and then try reordering them in the list

**SubTasks:**
- [ ]  Integrate UI so that it updates the habit list when user makes changes
- [ ]  Have the user drag habits to reorder them
- [ ]  Ensure this is saved between runs/activity switches
